PolymerElements/paper-input

bower.json
demo/index.html
paper-autogrow-textarea.html
paper-input-char-counter.html
paper-input-container.html
test/index.html
test/paper-autogrow-textarea.html

This is basically a copy cat of `paper-input` with an `iron-autogrow-textarea` instead of an `iron-input`. 
PTAL.
/cc @cdata

Paperify the iron-autogrow-textarea

---

bower.json
demo/index.html
demo/ssn-input.html
demo/ssn-validator.html
paper-input-behavior.html
paper-input-container.html
paper-input.html
paper-textarea.html
test/letters-only.html
test/paper-autogrow-textarea.html
test/paper-input-container.html
test/paper-input-error.html
test/paper-input.html

Enables using a custom input in a paper-input-container. Either
provide attr-for-value to observe input value changes for validation
and label floating, or if unset the `input` event is used. See demo
for an example.
Also enables iron-validator-behavior support. The validator takes
precedence over constraints, if provided.
Bind to more HTMLInputElement attributes.
Renamed paper-autogrow-textarea to paper-textarea to be more
consistent with paper-textarea.
@cdata @notwaldorf PTAL

support for custom validators and inputs

---

demo/index.html
paper-input-behavior.html
paper-input-container.html
test/paper-input-container.html

Added a `validate()` function to the behaviour, and refactored the `paper-input-container` to get notified (and care) when the contained `iron-input`'s validity changes. PTAL.
Needs https://github.com/PolymerElements/iron-input/pull/13 to work.

allow manual validation

---

paper-input-container.html

Fixes https://github.com/PolymerElements/paper-input/issues/28
On Firefox, because CSS, an invalid `iron-input` has a box-shadow and shows up with a red box around it (see issue). 
After the fix, it looks like the paper-input we know and love

fix native input's box-shadow

---

bower.json
paper-input.html
paper-textarea.html

Since the behavior was removed in https://github.com/PolymerElements/iron-input/pull/23, it needs to live in the custom element now. PTAL.

add form behaviour

---

paper-input.html

As discussed in https://github.com/PolymerElements/paper-input/issues/5,  the native `placeholder` color should be default to `--secondary-text-color`.  
**Note:**  there're a lot of rules here, I tried combining all the selectors in a single rule, but it stopped working. I think it broke something.
cc @cdata

Set placeholder default color to `--secondary-text-color`

---

paper-input-behavior.html
test/paper-input.html
test/paper-textarea.html

Added a helper formatting method (came up during https://github.com/PolymerElements/gold-phone-input/pull/16) that updates the value imperatively and preserves the caret position.

add formatting helper

---

paper-input-container.html
test/paper-input-container.html

Simpler to assert on `classList` instead of `getComputedStyle` with fewer platform issues.
@notwaldorf PTAL

Fix tests on Windows IE/FF

---

paper-input-behavior.html
paper-input.html

Added support for HTML5 datalists. This pull persists a list property as an attribute to the iron-input input element.

Added support for HTML5 datalists

---

paper-input-behavior.html
paper-input.html
paper-textarea.html

For https://github.com/PolymerElements/paper-input/issues/88 PTAL @notwaldorf

add autocapitalize/autocorrect ios safari attributes

---

paper-textarea.html

Since the `iron-autogrow-textarea` now registers to be added to an `iron-form` (https://github.com/PolymerElements/iron-autogrow-textarea/pull/18), we don't need to also register in `paper-textarea`
PTAL @morethanreal

don't duplicate registration to the iron-form

---

paper-input-error.html
test/paper-input-error.html

Fixes #95. The error is no longer role="alert" which means
it does not announce, but it's ok for a11y because the input
still has invalid and aria-describedby.
PTAL @notwaldorf

use visibility instead of display for error

---

bower.json
demo/index.html
paper-input-container.html
paper-input.html

New feature! This allows you to add a prefix/suffix element to the paper input (which in the long run should simplify all the duplication in the `gold-elements`). 
They look like this without input
And like this with input:
@morethanreal PTAL
P.S. All the tests are going to fail before https://github.com/PolymerElements/iron-form-element-behavior/pull/9 is merged :(

add prefix/suffix content selectors

---

paper-input-container.html

Otherwise suffixes/prefixes can push it up.
This doesn't affect normal inputs (sans any *-ixes), seeeeee:
Note that with or without this patch, a giant label looks terrible and floats below the line. Future-Monica should fix this in a separate PR. With magical text truncation. Or something:
/cc @morethanreal @cdata

label should always stick to the underline

---

paper-input-container.html

This allows styling the input and the -ixes (who may not necessarily be text) separately.
/cc @morethanreal @cdata

add prefix/suffix custom props

---

demo/index.html
paper-input-behavior.html
paper-input-container.html

Validating on `attached` is a little weird, since it results in you looking at a form with all red fields you haven't really touched.
🎷@cdata

validate inputs on blur instead of attached

---

paper-input-container.html

Hello,
My team is building a mobile webapp using polymer. We managed to achieve very good performance by carefully measure and optimize bottlenecks. One of them is the number of graphical layers/GPU memory/Compositing. We found that the paper inputs have unnecessary layers due to the use of translate3d.
Thanks

Replace translate3d by translateY

---

demo/index.html
paper-input-behavior.html
paper-input-container.html
paper-input.html

As usual, `<input type=...>` is a jar of spiders. In today's re-enactment, `type=search` has hilarious and inconsistent styles across browsers. This PR makes it sort of work with `paper-input` (and sorta fixes https://github.com/PolymerElements/paper-input/issues/178). The end result is:
Chrome:
FF: (look how nice it is. sigh)
Safari:
Safari also successfully displays the spyglass, but I haven't managed to trick the other 2 to do that:
If you don't listen to the instructions and use a non-floated label, it looks amazing and there's nothing really that we can do about this (aside from putting in logic that forces you to auto-float the label if type="search". @cdata Should we do that? Sigh):
I don't know what it looks on IE, but it's probably fine, right?
`<input>` or: why we can't have …

make type=search less terrible

---

paper-input-container.html

This fixes the comment in https://github.com/PolymerElements/paper-input/issues/167#issuecomment-143912219
We don't really care about the `offsetParent` unless we have a prefix, so the `if` statement should bail out early if we don't.
I also think the `this.$.prefix` bit is always true because it just points to the `content` node, so I don't think it's needed.

less offsetParent recalc

---

paper-input-error.html

This was introduced because of https://github.com/PolymerElements/paper-input/pull/183
Turns out the point of the `float` was to pull the next input up and not add extra spacing. 
Proof that it looks nice now:
Floats: :skull:

fix extra input-error spacing regression

---

demo/index.html
paper-input-container.html

Fixes https://github.com/PolymerElements/paper-input/issues/192 with :sparkles: css magic :sparkles: 
Look at the nice truncated label:
And we get extra space when we float:
Unrelated: I've also deleted the `type=search` example from the demo, even though I just added it. It looks kind of weird, and we don't demo every other `type=`, so there's really no point (it does nothing special)

fix long labels on small screens

---

paper-input-container.html

Updated the names of mixins incorrectly documented.
Fixes https://github.com/PolymerElements/paper-input/issues/180
As discussed in the issue, the suffix/prefix names are not consistent with the other `paper-input-container-*` names, but I think changing them might break existing code (where people have figured out what mixins to use correctly), which is not really worth it. So this is just making the docs not lie.

fix mixin docs

---

paper-input.html

A comma in the middle of attribute declarations for
`<input is="iron-input" ...>` was causing html-minifier to spin in an
endless loop.

Removed comma syntax error

---

paper-textarea.html

This just rebases and lands https://github.com/PolymerElements/paper-input/pull/191, which seems to have falled off the radar :)

bind disabled attribute

---

paper-input-behavior.html
paper-input.html

Fixes https://github.com/PolymerElements/paper-input/issues/206
`<input>`: the gift that keeps on giving.

add attributes for input type=file

---

paper-input-container.html
paper-input-error.html

Fixes issue https://github.com/PolymerElements/paper-input/issues/106
Depends on https://github.com/PolymerElements/iron-autogrow-textarea/pull/51 when shadow dom is used.
Allows alignment of <code>paper-input, paper-textarea, paper-input-container</code> to be applied to the children (aka children will inherit the text-align from the container)
With this PR, users will be able to apply styles like:
```css
paper-textarea,
paper-input,
paper-input-container {
text-align: center;
}
```
- takes care of placement of the label, input
- takes care of add-on-content
Known issue: alignment of the label when paper-input has prefix/suffix content (to be tackled in a separate PR)

input inherits the text-align from the container

---

paper-input-container.html

Ohhhhh boy. This PR. So many things:
- Fixes whatever is left of https://github.com/PolymerElements/paper-input/issues/167, because we :bomb: `offsetParent`
- We no longer do a really gross offset calculation if there's a prefix AND it still looks good because future monica knows more CSS than past monica:
- Fixes https://github.com/PolymerElements/paper-input/issues/149 because we now know when the prefix has been added and removed! :two_hearts:

fix prefix-related CSS

---

demo/index.html
paper-input-char-counter.html
paper-input-container.html

Flip ALL the things!
Normal inputs:
Inputs with character counters and error messages:
Suffixes and prefixes:

make it RTL friendly

---

paper-input-char-counter.html
paper-input-container.html
paper-input-error.html

Removes any use of the `/deep/` flex classes. One step closer away from dragons 🐉🎉 
Before:
After:
And hopefully nothing else :(
(I would release this as a minor version bump, P.S)

stop bringing in the paper-styles kitchen sink

---

bower.json
paper-input-container.html
test/paper-input-container.html

Fixes https://github.com/PolymerElements/paper-input/issues/228. Looking at the code some more, I think we don't need to listen to children at all, and just fix the floating label style to always align to the edge (which is a no-op if there's no prefix)
Bumped down the polymer dependency version as a result.

fix prefix even moar better

---

paper-input-container.html

Just fixed a typo in the `paper-input-container` documentation.

Fix documentation typo.

---

paper-input-container.html

This way the prefixes, sufixes and the label will be aligned vertically (vs. aligned at the bottom, which makes them look sad)
/cc @ebidel

center the input-related-elements vertically

---

bower.json

Fixes #281 
The component `paper-input-addon-behavior.html` was added to main since `paper-input-error` requires it.

added paper-input-addon-behavior to main

---

paper-input.html
paper-textarea.html

I added "overflow: hidden" to paper-input and paper-textarea to prevent the scrollbar.
This is a variant of robrez's fix in #277.
Not sure of the larger implications of this change.

paper-input temporarily creates a horizontal scrollbar after typing first letter #277

---

paper-input-container.html
paper-input.html
paper-textarea.html

fixing temporary scrollbar again
Removing the overflow hidden that killed the error labels.
Changing width to animate with scaling so the strange width:133% + scale(0.75) stuff will be applied at the same rate. Had to apply an initial width to get this to work.
I tested on windows in chrome, IE and Edge.
Didn't notice any issues.

paper-input temporarily creates a horizontal scrollbar after typing first letter #277 #294

---

paper-input-behavior.html

Fixes https://github.com/PolymerElements/paper-input/issues/260
Since the behaviour docs appear in the `<paper-input>` page, there's some confusion about what "bind this to the iron-input" actually means (since you don't actually have an iron-input, as an user). Cleared up the docs to explain this only matters if you're using the behaviour to roll out your own element.

add more deets to the behaviour docs

---

paper-input-behavior.html
paper-input.html
test/paper-input.html

Fixes #291 .
Despite saying in the docs you shouldn't do this, it's a bit surprising when the label overlaps some native input's default placeholder (things like `type="date"` always have a placeholder). So I'm admitting defeat and fixing this, and auto-floating the label in that case.

Autofloat label for special types

---

paper-input.html

This PR attempts binds the title attribute that a paper-input is invoked with to the title attribute of the native input element in its template. This is useful because when you provide a pattern attribute that is not matched by the user's input, the browser will show your title to the user to help them figure out how to correct their input.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
> Use the title attribute to describe the pattern to help the user.
See also "Title Attribute" section of http://www.html5rocks.com/en/tutorials/forms/constraintvalidation/

bind title attribute

---

paper-input-behavior.html
test/paper-input.html
test/paper-textarea.html

- fixes https://github.com/PolymerElements/paper-input/issues/321
- uses the overriden `_focusBlurHandler` from `IronControlState` instead of redefining a `focus` handler
- hopefully cleans up the tests so that they make more sense, and add a giant comment about what the current state of focus/blur is
- removes a test from `paper-textarea` because it was from before the time when textarea didn't have a tabindex by default

clean up focus/blur tests

---

paper-textarea.html

Fixes https://github.com/PolymerElements/iron-autogrow-textarea/issues/33
This is part of a 3-headed hydra of PRs that is trying to fix the following problem: `iron-form` was bad at de-duping nested elements with the same `name`, and would double submit them. The problem was that if you bind the `name` attribute all the way down, and these children you're binding it to are either native elements (so the form automatically cares about them) or custom elements with the `IronFormElementBehavior`, you would submit the same value twice.
This PR adds the correct `IronFormElementBehavior` to the element, since it's an element that wants to work in a form, and that's what the behavior does.
Landing this without the other 3 means that a `paper-textarea` will be submitted twice.
Related PRs:
- …

add IronFormElementBehavior to paper-textarea

---

paper-input-addon-behavior.html
paper-input-char-counter.html
paper-input-error.html

Hello,
This fixes a closure compiler issue when we compile this with the Chromium settings.
Note, that this header is duplicated text from PaperInputAddonBehavior. I tried using @override, but that did not work. I'm open to suggestions if there's a better way to do this.
If accepted, can we also roll the version so Chromium can pull the new version of paper-input? Thanks.
Tommy

Fix closure compiler error (using Chromium settings).

---

paper-input-container.html

Doc update to warn against wrapping elements that already use paper-input-container.

---

paper-input-behavior.html

I moved the global ID variables to Polymer, but I'm willing to accept any other strategy that keeps the definition of PaperInputBehaviorImpl outside a closure.

jscompiler doesn't like behaviors being defined in a closure

---

paper-input.html

when user moved back/forward value in the field is not saved, although standard browser behaviour is to save state/value of input fields 
fixed for Safari/Firefox (Chrome didn't have this issue)

fixed browser back/forward input field value

---

paper-input.html

Reverts PolymerElements/paper-input#368, since it causes https://github.com/PolymerElements/paper-input/issues/377.

Revert "fixed browser back/forward input field value"

---

paper-input-container.html
paper-input.html
paper-textarea.html

Fixes https://github.com/PolymerElements/paper-input/issues/231
The label can be `aria-hidden` since it's already being read out as part of the `input`'s `aria-labelledby`.
Don't merge yet: currently blocked on https://bugs.chromium.org/p/chromium/issues/detail?id=595494

aria-hide the label since it's not needed

---

paper-input-behavior.html
test/paper-input.html

This PR fixes clearing of the `focused` attribute when the blur occurs as a result of `shift-tab` key combination. Basically this was fixed by always calling the `_focusBlurHandler` of `IronControlState` even when the `_shiftTabPressed` flag is set.

Clear the focused attribute on blur from shift-tab. Fixes #386

---

paper-input-behavior.html
test/paper-input.html

The fix here was made unexpectedly challenging by some odd activeElement results in IE 11.

If autofocus is set to true, implicitly take focus. Fixes #166.

---

paper-input.html

Fixing #408
Adding aria-live="assertive" to the error message in paper-input.

Fixing #408: A11y: Upon showing an error using error-message attribute no verbalisation is given.

---

paper-input.html

In the chrome html.css an outline is added on focused. The paper-input already has a way of focusing (the blue underbar) that doesn't involve the outline box. The outline box is redundant and distracting.
Fixes #415

Remove default outline

---

paper-input.html
paper-textarea.html
test/paper-input.html
test/paper-textarea.html

Fixes #418 by disabling pointer events for `label` in `paper-input` and `paper-textarea`.
This is not done in `paper-input-container` as it might remotely be a breaking change for whoever is counting on pointer events on the label. Moreover, users of `paper-input-container` can already disable pointer events by using the mixin `--paper-input-container-label`

no pointer events for label

---

paper-textarea.html

This prevents the invalid property from getting out of sync when it it for example set from an outside component.

Add missing binding for invalid property to paper-textarea.

---

paper-input-behavior.html

Correct date string example in max documentation

---

paper-input-container.html

Was facing the same issue and saw there was already an issue open for it. I have tested it in my application and it is working perfectly with:
``` css
paper-input[type="number"] {
--paper-input-container-input-webkit-spinner: {
-webkit-appearance: none;
margin: 0;
}
}
```
Fixes #279

Add CSS mixing for webkit spinner

---

paper-input-container.html

addresses https://github.com/PolymerElements/paper-input/issues/448

Implement underlines with border rather than height/width for better rendering at non-standard zoom

---

paper-input-error.html

This change allows user to set the position css property of the `paper-input-error element`.

Move css mixins to bottom of the rules-block in paper-input-error element

---

paper-input-error.html

Reverts PolymerElements/paper-input#506 because CLA wasn't signed

Revert "Move css mixins to bottom of the rules-block in paper-input-error element"

---

paper-input-container.html
paper-input.html
test/paper-input-container.html

Surface default (`:host`) and focused (`:host([focused])`) targeted mixin implementations for the component.
references #463

Implementat @apply mixins to control styling

---

paper-textarea.html

pass the validator attribute to iron-autogrow-textarea make possible to use custom validator

pass validator attribute to iron-autogrow-textarea make possible to use custom validator

---

paper-input-container.html

There are missing quotes around an HTML tag in paper-input-container documentation, which is causing the HTML tag be interpreted on browsers.

Fix a typo in the documentation of paper-input-container.

---

paper-input-container.html

Tested on iPhone 5S/iOS 11.0.2

master - fixes #352 safari hack: focusing input w/ 0 height

---

paper-input.html
test/paper-input.html

Safari's user agent stylesheet adds a 4px margin-top and margin-bottom for inputs. This removes that and fixes #520 
Left is Chrome, right is Safari. Before:
After:
Only affects `<paper-input>`, `<paper-textarea>` is fine.

Remove extra margin from Safari user agent stylesheet

---

README.md
paper-input.html

This fixes #563 by providing a style mixin to override ::-ms-reveal for custom styles.

This fixes #563 by providing a style mixin to override ::-ms-reveal for custom styles.

---

paper-input-container.html
paper-input.html

Fixes #539
This fixes #539 adding a mixin `--paper-input-container-input-disabled` to be applied on the input element when the `paper-input` is disabled.

Added mixin to be applied on input:disabled

---

paper-input-char-counter.html
paper-input-container.html

- fixes #593: there was a TODO from like a year ago that made the effective width of the floated label in RTL smaller.
- Added `:dir` selectors so that this actually works in Polymer 2 with the polyfill (it doesn't on master)
There seems to be a separate bug where in Polymer 2 this still doesn't look perfectly right on Safari (the label is offset weirdly), but I am suspicious that's unrelated and a polyfill problem.

fix label width in rtl; add :dir for polymer 2

---

paper-input-char-counter.html
paper-input-container.html
paper-input.html

Fixes #597, fixes #593 again.
Previous PR on this topic #594 did a bad (I did the bad). It added `overflow:hidden` which actually cut off the input and made it look like this:
This PR correctly fixes the original RTL problem (which was that the label-come-down-from-floating-to-not-floating animation overflowed in the container) by correctly setting the overflow direction (which is backwards, thanks @bicknellr for spotting that)
Not floated (ltr and rtl):
Floated:
And as a bonus does the thing that @azakus said we should do which is just use `:dir` errwhere because it works in 1.0 as well.
It takes a village, fam.

Fix overflow:hidden bug I introduced in the previous PR 

---

.travis.yml
test/paper-input.html
wct.conf.json

Ok these tests have been on 🔥 for a bit too long and it makes Travis useless, and it needs to end. :sob:.
On 1.x we get an error on the `a11ySuite` shadow dom, paper-input tests:
```
Error: AX_ARIA_04 (ARIA state and property values must be valid) failed on the following element:
#input
See https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_04 for more information.
```
As far as I can see this is a false negative. Lighthouse on a `paper-input` doesn't find any errors, so I think it's a problem with the library we're using. Nobody is really maintaining either that, nor `a11ySuite`, and we should really migrate to axe core, so in the interest in trying to have useful Travis results (i.e. not permanently red for things we can't fix), I'm disabling these …

Fixes for broken tests

---

paper-input-behavior.html
paper-input.html
paper-textarea.html

The 2.x PR is here: https://github.com/PolymerElements/paper-input/pull/609
Fixes #600: Chrome has recently started throwing some auditing errors in the console if any `<input type="password">` has the same `id` as any other `input`. This means that in Shady DOM, if you have two `paper-inputs` on a page, you'd get this error. This fixes that by generating unique IDs for the inputs in the page.
(this is PR https://github.com/PolymerElements/paper-input/pull/602 with like one extra commit on it, thanks @ipuiu for doing all the work!)

1.x: Generate unique IDs for the input in the shadow root

---

paper-input-behavior.html
paper-input.html
paper-textarea.html

The 1.x PR is here: https://github.com/PolymerElements/paper-input/pull/608
Fixes #600: Chrome has recently started throwing some auditing errors in the console if any `<input type="password">` has the same `id` as any other `input`. This means that in Shady DOM, if you have two `paper-inputs` on a page, you'd get this error. This fixes that by generating unique IDs for the inputs in the page.

2.x: Generate unique IDs for the input in the shadow root

---

paper-input-container.html
paper-input.html

With ::shadow soon to be no longer supported in Chrome, I needed another way to access the calendar picker indicator. This change makes it consistent with the other two icons alongside it, the clear and spin buttons.

Added a mixin for calendar picker indicator for date type input

---

demo/index.html
paper-input-container.html
paper-input.html

Fixes #638, #636, #613.
It's hard to add a test for this, so I've added a super complex `demo-snippet`:

styles not applied to slotted input in 2.x

---

demo/index.html
paper-input-container.html
paper-input.html

#639 changed how the `iron-input > input` inherits styles, but didn't inherit `color` correctly. @sorvell  says there's a shim limitations where you can't have custom properties inside of an `@apply`, so that's why the custom property inside of the `paper-input-container-shared-input-style` mixin doesn't actually get applied

fix color not inheriting

---

paper-input.d.ts
paper-input.html

As a result of a TypeScript update in `IronFormElementBehavior` (https://github.com/PolymerElements/iron-form-element-behavior/pull/41) to address an issue in `paper-slider` (https://github.com/Polymer/gen-typescript-declarations/issues/103) this inadvertently broke the compilation of `paper-input`. The fix is the same as for `paper-slider`, declare `value` again with the correct type in the concrete subclass.
Fixes #645

Fix TypeScript compilation of paper-input

---

.travis.yml
demo/ssn-input.html
demo/ssn-validator.html
package-lock.json
package.json
paper-input-addon-behavior.d.ts
paper-input-addon-behavior.html
paper-input-behavior.d.ts
paper-input-behavior.html
paper-input-char-counter.html
paper-input-container.d.ts
paper-input-container.html
paper-input-error.html
paper-input.d.ts
paper-input.html
test/letters-only.html
test/paper-input-char-counter.html
test/paper-input-container.html
test/paper-input-error.html
test/paper-input.html
test/paper-textarea.html

Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.
What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more!

Automatic format!

---

paper-input-container.html

This resolves issues [134](https://github.com/PolymerElements/iron-input/issues/134) and [655](https://github.com/PolymerElements/paper-input/issues/655) introduced from [PR 130](https://github.com/PolymerElements/iron-input/pull/130).
Allowing '' here (along with undefined) should not create any issues because it is only checking once on startup.  The alternative is to revert PR 130 but I am not sure why setting a default was needed.

Fixes Auto-Validation fires directly for required without any user interaction

---

paper-input-addon-behavior.html

Fixes #580.
This line says it's a workaround for https://github.com/webcomponents/shadydom/issues/96, which looks fixed.

remove call to polymer.dom.flush

---

paper-textarea.d.ts
paper-textarea.html

fix types on paper-textarea. This is due to the closure fix in PolymerElements/iron-form-element-behavior#47

fix paper-textarea types

---

test/paper-input.html

Firefox seems to have a bug where calling `blur` on an element with a ShadowRoot containing a focused element doesn't do anything. This checks for the bug and skips the test if present.

Skip a 'blur' event test if the browser has a bug that would prevent it from working.

---

paper-input-error.js

Hide the content of paper-input-error elements with `invalid === false` using `visibility: hidden;` on an internal wrapper element so that it isn't read by screen readers even if the paper-input-error is referenced by an `aria-describedby` attribute.

Prevent error messages from being read by screen readers when the input is not in an error state.

---

.travis.yml
paper-input-behavior.js

For compatibility with the type of HTMLElement#autocapitalize which, in TypeScript at least, is just `string` not `string|null|undefined`
Downstreamed as cl/221176969

autocapitalize should not have a nullable type

---

paper-input.js

This is part of PolymerElements/paper-dropdown-menu#317, which needs to set these to be able to continue using paper-input for the sake of styling but also allow paper-input's wrapped input to act as the focusable element while being read by screen readers as a button rather than a text input.

Add properties to allow setting the internal input's ARIA role and aria-haspopup attribute.

---

paper-input-behavior.js

In TypeScript 3.8 a new property `autofocus` was introduced on `HTMLElement`. When a component like [`gold-phone-input`](https://github.com/PolymerElements/gold-phone-input/blob/master/gold-phone-input.js) extends both this behavior and `HTMLElement` the `autofocus` properties now conflict. This change marks `autofocus` as non-nullable to align with TypeScript's `HTMLElement`.
Here's a playground link demoing the issue: http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIgA4FcwCEIAWcAbsAPZTIDeAUMvcnDmTGQlgM4BcyARmWQA2EOCGQAfZCCyDBE5FhAATCDFAQlAbhoBfGjVCRYiFAAUCZEBHTYwyCAA9Iyjmkw58RUhQA0yABIAKgCyADIAosIAthDg1HQMujRAA
To see past behavior set the version to 3.7.5, and the current by setting the version to 3.8.3.

Update autofocus property to be non-nullable
