PolymerElements/paper-input

README.md, bower.json, demo/index.html, index.html, paper-input-char-counter.html, paper-input-container.html, paper-input-error.html, paper-input.html, test/index.html, test/paper-input-char-counter.html, test/paper-input-container.html, test/paper-input-error.html, test/paper-input.html
=> implement add-ons, error message, character counter

demo/index.html, paper-input-container.html, paper-input.html
@cdata @notwaldorf PTAL
I don't have a test, but there seems to be no way to send key events to the input and have it alter the value :(
=> add type attribute

paper-input-container.html, paper-input-error.html
=> fix error not showing with type="number"

bower.json, paper-input-container.html, test/paper-input.html
=> all tests pass on osx!

test/paper-input.html
Fixes https://github.com/PolymerElements/paper-input/issues/11
=> Fix failing test

paper-input-container.html
Fixes https://github.com/PolymerElements/paper-input/issues/10
=> fix layout classes

demo/index.html, paper-input-container.html, paper-input.html
Fixes https://github.com/PolymerElements/paper-input/issues/16
=> add a disabled property

paper-input-behavior.html, paper-input.html
=> add paper-input-behavior

paper-input-container.html, paper-input-error.html
=> use custom property defaults

demo/index.html
Added a small example to prove it works :)
=> add placeholder example

paper-input.html
=> set display:block

all-imports.html, bower.json, demo/index.html, demo/ssn-input.html, index.html, paper-input-addon-behavior.html, paper-input-behavior.html, paper-input-char-counter.html, paper-input-container.html, paper-input-error.html, paper-input.html, paper-textarea.html, test/index.html, test/paper-input-char-counter.html, test/paper-input-container.html, test/paper-input.html, test/paper-textarea.html
=> bug fixes, add docs, etc.

demo/ssn-input.html, paper-input-behavior.html, paper-input.html, paper-textarea.html, test/paper-input-container.html, test/paper-input.html, test/paper-textarea.html
=> add aria-label

paper-input-container.html
=> fix input min width

demo/index.html, paper-input-behavior.html, paper-input.html, paper-textarea.html, test/paper-input.html, test/paper-textarea.html
For #5. @notwaldorf PTAL cc @cdata
=> add aria-describedby

test/paper-input-container.html
=> fix tests for ie10

paper-input.html
Changed the attribute for iron-input to allow the passing of allowed-pattern
=> allowedPattern -> allowed-pattern

bower.json, paper-textarea.html, test/paper-textarea.html
=> bind more attributes to iron-autogrow-textarea

demo/index.html, paper-input-behavior.html, paper-textarea.html, test/paper-input.html, test/paper-textarea.html
For https://github.com/PolymerElements/paper-input/issues/69
@notwaldorf PTAL
=> Fix always-float-label

test/paper-input.html
Add a test case for https://github.com/PolymerElements/paper-input/issues/68
=> test case for two-way binding the invalid attribute

paper-input-container.html, test/paper-input-error.html
Workaround until https://github.com/Polymer/polymer/issues/1773 is landed. For https://github.com/PolymerElements/paper-input/issues/53 PTAL @notwaldorf
=> workaround unpredictable attached ordering

bower.json, paper-input-behavior.html, paper-input.html, test/paper-input.html, test/paper-textarea.html
For https://github.com/PolymerElements/paper-input/issues/59 PTAL @cdata
Needs https://github.com/PolymerElements/iron-autogrow-textarea/pull/12 before merging.
=> use IronControlState

paper-input.html
:wrench: the form behaviour that got accidentally :scissors: in https://github.com/PolymerElements/paper-input/pull/83
=> add back form behaviour

paper-input-container.html
Resolves #61. PTAL @notwaldorf
=> add styling mixins for label and underline

paper-input-behavior.html, test/paper-input-container.html, test/paper-input.html, test/paper-textarea.html
Resolves #99 and also make all tests green. See code comment for more details. PTAL @notwaldorf
=> Fix focus state in paper-input

paper-textarea.html
=> fix unnecessary observer

test/paper-input.html, test/paper-textarea.html
=> Don't be too picky about how many events we get.

paper-input-container.html
Very small change in the comments.
=> Ammend comments to be reflective of actual color use

paper-input-container.html
Fix for https://github.com/PolymerElements/paper-input/issues/114
Along with
https://github.com/PolymerElements/iron-input/issues/37
https://github.com/PolymerElements/iron-input/commit/686228e01e6950b79c501e4cdf4f9bf17793f09a
=> Show value when value is 0

paper-input-container.html
=> add disabled input mixin

paper-input-container.html
Fixes https://github.com/PolymerElements/paper-input/issues/85
@cdata PTAL
=> make focused a notify property

paper-textarea.html
Fixes https://github.com/PolymerElements/paper-input/issues/153
(@cdata as an FYI)
=> paper-textarea should be display:block

paper-input-behavior.html
=> make invalid a notify property

bower.json, paper-input-behavior.html, paper-input.html, paper-textarea.html
This was originally opened in https://github.com/PolymerElements/paper-input/pull/142, but @blasten doesn't have time to finish it right now, so here we are.
:pager: @cdata
=> propagate the change event correctly

paper-input-container.html
Fixes https://github.com/PolymerElements/paper-input/issues/174
=> words have meanings

paper-input-error.html
Fixes https://github.com/PolymerElements/paper-input/issues/175
(tldr: i don't know why that float is there, and taking it away makes everything look the same, minus borking anything that comes after it and is affected by the float)
=> remove uneeded error float

README.md
Here's a first pass at an autogenerated README! See it rendered here: https://github.com/PolymerElements/paper-input/tree/auto-cleanup
This is generated in a super straightforwards way, hydrolysis made it super easy.
The main improvement I'd like to add is syntax highlighting to the code examples.
@cdata @tjsavage and @garlicnation are likely interested too.
=> Autogenerate README file.

paper-input-behavior.html
Fixes https://github.com/PolymerElements/paper-input/issues/202
=> make polylint happy

paper-input.html
Polymer.IronControlState is already inherited in Polymer.PaperInputBehavior
=> Polymer.IronControlState duplicate inheritance

paper-input-behavior.html
=> Fixes Issue #249

bower.json, demo/index.html, paper-input-behavior.html, paper-input.html, paper-textarea.html, test/paper-input.html, test/paper-textarea.html
As requested in https://github.com/PolymerElements/paper-input/issues/129 cc @notwaldorf @frankiefu
=> Add focus method

paper-input-container.html
=> Fix #229 - css mixin for floating label with docs

bower.json, demo/index.html, test/paper-input-char-counter.html, test/paper-input-container.html, test/paper-input-error.html, test/paper-input.html, test/paper-textarea.html
Here's a fancier demo. I am worried we are covering too many examples? What do you think?
/cc @addyosmani for input
(I've also updated the tests to the wct of the future, etc, etc)
=> prettify the demo

demo/index.html
- Remove paper-input-char-counter.html import because is unused
- Fix rel attribute from color.html
=> Remove unused import and fix rel attribute

paper-input-container.html
Fix for issue ..
https://github.com/PolymerElements/paper-input/issues/275
=> Use flex-auto to fix IE

bower.json
=> Bump required version of Polymer

paper-input-container.html
Review/Retest: https://github.com/PolymerElements/paper-input/pull/276#issuecomment-168794783
Fixes: https://github.com/PolymerElements/paper-input/issues/214
=> Fix sizing issues

bower.json, paper-input-container.html
=> Update to the new paper theme colors

paper-input-char-counter.html, test/paper-input-char-counter.html
Reference: https://github.com/PolymerElements/paper-input/issues/271
=> Fix char counter for the textarea's new lines

paper-input-error.html
Missed in https://github.com/PolymerElements/paper-input/pull/335
=> Add missing import: paper-styles/default-theme.html

bower.json, demo/ssn-input.html
=> Fix SSN input layout in demo

paper-input-container.html, test/paper-input-container.html
Fixes https://github.com/PolymerElements/paper-input/issues/313
=> set up children listeners in attach not ready

paper-input-behavior.html, test/paper-input.html
Fixes https://github.com/PolymerElements/paper-input/issues/113
Most of the changes are indentation; use https://github.com/PolymerElements/paper-input/pull/356/files?w=1 to ignore whitespace changes.
=> use monotonically increasing IDs for the labels

paper-input-container.html
These missing backticks result in some missing text in the API docs.
=> Add missing backticks

bower.json
=> Bump required version of paper-styles

demo/ssn-input.html, paper-input-char-counter.html, paper-input-container.html, paper-input.html, paper-textarea.html
=> Ensure hidden attribute works.

paper-input-char-counter.html, test/paper-input.html
This is a simple fix for issue #364.
=> Fix #364: Make char-counter work with Numbers

paper-input-container.html, test/paper-textarea.html
Fixes #394 
I allowed myself to sync the already existing PR,  because it's highly needed and the original PR was stuck from more than half a year with no response from the author.
=> Change paper-textarea to have the same height as paper-input.

paper-textarea.html
Need https://github.com/PolymerElements/iron-autogrow-textarea/pull/87
=> Add minlength property

bower.json
=> remove trailing comma in bower json

paper-input-container.html, paper-input.html
This should close #501. I used #495 as a reference.
=> Add ::-ms-clear mixin

paper-input-behavior.html
Fixes https://github.com/PolymerElements/paper-input/issues/529
=> don't autoselect text on click

paper-input-behavior.html
Whatcha think, fam? Hows da English?
=> Fix input type docs

paper-input-container.html
=> 1.x backport of PR #585

paper-input-container.html, test/paper-input.html
=> Fix label not resetting on undefined

test/paper-input-char-counter.html, test/paper-input-container.html
- Added missed slot attributes
=> Added missed slot attributes

paper-input-container.html, paper-input.html
This change has already been merged into master, but it is also needed on 1.x.
=> Added mixin for calendar picker indicator for date type input

paper-input.html
=> inherit cursor property

.travis.yml, package-lock.json, paper-input-behavior.d.ts, paper-input-behavior.html
related PolymerElements/iron-form-element-behavior#47
This is because one often extends both this behavior and iron form element behavior at the same time. This causes TS issues when their types diverge
=> Change ts type to any

demo/index.html, paper-input-container.js
=> append style to head not body

paper-input.js
=> Minor Closure compilation fix
